const SESSION="veyltharyn_session",DB="veyltharyn_github_db";
function getUser(){try{return JSON.parse(localStorage.getItem(SESSION)||'null')}catch(e){return null}}
function requireUser(){const u=getUser();if(!u){location.href='login.html';throw new Error('Silakan login terlebih dahulu.')}return u}
function db(){let d=JSON.parse(localStorage.getItem(DB)||'{}');d.users??=[];d.products??=[];d.orders??=[];d.vouchers??=[];d.notifications??=[];d.chats??=[];d.messages??=[];d.spins??={};d.coins??={};d.audit??=[];d.warnings??=[];d.settings??={siteTitle:'Veyltharyn',siteSubtitle:'Dark Fantasy Gaming Platform',announcement:'',background:'',overlay:0.28,accent:'#b3002d',accent2:'#ff1744',maintenance:false,serverIp:'vn-play.myftp.biz',serverPort:'21374',serverVersions:'1.21.x, 1.20.x, PM4, PM5'};d.music??=[];d.chatClaims??={};d.discounts??=[];return d}
function saveDb(d){localStorage.setItem(DB,JSON.stringify(d))}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function uid(prefix){return prefix+'-'+Math.random().toString(36).slice(2,9).toUpperCase()}
function today(){return new Date().toISOString().slice(0,10)}
async function api(a,o={}){const d=db(),u=getUser();const qs=o.qs||{};const body=o.body instanceof FormData?Object.fromEntries(o.body.entries()):(o.body||{});if(!d.settings)d.settings={};if(!d.warnings)d.warnings=[];if(!d.music)d.music=[];if(!d.chatClaims)d.chatClaims={};if(!d.discounts)d.discounts=[];if(['me','coins','claim-coins','gacha-status','gacha-spin','my-vouchers','orders','notifications','notifications-read','chats','messages','send-message','chat-create','order','voucher-check','report','my-products','create-product','delete-product','order-status'].includes(a)) requireUser();
if(a==='me')return{user:u};
if(a==='products'){let p=d.products.filter(x=>x.status!=='deleted');if(qs.q)p=p.filter(x=>(x.name+' '+x.product_id+' '+x.description).toLowerCase().includes(String(qs.q).toLowerCase()));if(qs.category)p=p.filter(x=>x.category===qs.category);return{products:p.map(x=>({...x,seller:(d.users.find(z=>z.id===x.seller_id)||{}).username||'Seller'}) )};}
if(a==='product'){const p=d.products.find(x=>x.product_id===qs.id&&x.status!=='deleted');if(!p)throw new Error('Produk tidak ditemukan.');return{product:{...p,seller:(d.users.find(z=>z.id===p.seller_id)||{}).username||'Seller',seller_verified:false}}}
if(a==='my-products'){const manager=['owner','admin','admin_cs','staff'].includes(u.role);return{products:d.products.filter(x=>x.status!=='deleted'&&(manager||x.seller_id===u.id))};}
if(a==='create-product'){let photo='';if(body.photo&&typeof body.photo==='object'&&body.photo.data){photo=String(body.photo.data).slice(0,1500000)}else if(typeof body.photo==='string'&&body.photo.startsWith('data:image/')){photo=body.photo.slice(0,1500000)}const p={id:Date.now(),product_id:uid('VND'),seller_id:u.id,name:String(body.name||'').trim(),description:String(body.description||'').trim(),price:Number(body.price||0),category:String(body.category||'Lainnya').trim(),photo,whatsapp:String(body.whatsapp||'').trim(),seller_email:String(body.email||u.email||'').trim(),status:'active',created_at:new Date().toISOString()};if(!p.name||p.price<0||!p.description)throw new Error('Data produk belum lengkap.');d.products.push(p);saveDb(d);return{ok:true,product_id:p.product_id}}
if(a==='delete-product'){const manager=['owner','admin','admin_cs','staff'].includes(u.role);const p=d.products.find(x=>x.product_id===body.product_id&&x.status!=='deleted'&&(manager||x.seller_id===u.id));if(!p)throw new Error('Produk tidak ditemukan atau akses ditolak.');p.status='deleted';p.deleted_by=u.id;saveDb(d);return{ok:true}}
if(a==='coins'){const c=d.coins[u.id]||{balance:0,last_claim:null};return{balance:c.balance||0,last_claim:c.last_claim}}
if(a==='claim-coins'){const c=d.coins[u.id]||{balance:0,last_claim:null};if(c.last_claim===today())return{ok:false,message:'VNCoins hari ini sudah diklaim.'};c.balance=(c.balance||0)+1;c.last_claim=today();d.coins[u.id]=c;saveDb(d);return{ok:true,balance:c.balance,message:'VNCoins +1'}}
if(a==='gacha-status'){const c=d.coins[u.id]||{balance:0},s=d.spins[u.id]||{};const n=s.date===today()?s.count:0;return{balance:c.balance||0,spins_today:n,spins_left:Math.max(0,3-n)}}
if(a==='gacha-spin'){const c=d.coins[u.id]||{balance:0},s=d.spins[u.id]||{};const n=s.date===today()?s.count:0;if((c.balance||0)<1)throw new Error('VNCoins tidak cukup.');if(n>=3)throw new Error('Batas 3 spin per hari tercapai.');c.balance--;d.coins[u.id]=c;const r=Math.floor(Math.random()*100)+1;let disc=r===1?95:r<=20?50:r<=45?30:r<=75?20:5;const v={id:Date.now(),code:uid('VNC'),owner_id:u.id,discount_percent:disc,expires_at:new Date(Date.now()+7*864e5).toISOString(),status:'active'};d.vouchers.push(v);d.spins[u.id]={date:today(),count:n+1};d.notifications.push({id:Date.now()+2,user_id:u.id,title:'Gacha berhasil',body:`Kamu mendapat voucher ${disc}% OFF — ${v.code}`,is_read:false,created_at:new Date().toISOString()});saveDb(d);return{ok:true,discount_percent:disc,voucher_code:v.code,expires_at:v.expires_at}}
if(a==='my-vouchers')return{vouchers:d.vouchers.filter(x=>x.owner_id===u.id&&x.status==='active')}
if(a==='voucher-check'){const v=d.vouchers.find(x=>x.code===qs.code&&x.owner_id===u.id&&x.status==='active');if(!v)throw new Error('Voucher tidak valid.');const p=d.products.find(x=>x.product_id===qs.product_id);if(!p)throw new Error('Produk tidak ditemukan.');const dis=Math.floor(Number(p.price)*v.discount_percent/100);return{discount_percent:v.discount_percent,discount_amount:dis,final_price:Number(p.price)-dis}}
if(a==='order'){const p=d.products.find(x=>x.product_id===body.product_id&&x.status!=='deleted');if(!p)throw new Error('Produk tidak ditemukan.');if(p.seller_id===u.id)throw new Error('Tidak bisa membeli produk sendiri.');let final=Number(p.price),discount=0,v=null;if(body.voucher_code){v=d.vouchers.find(x=>x.code===body.voucher_code&&x.owner_id===u.id&&x.status==='active');if(!v)throw new Error('Voucher tidak valid atau sudah digunakan.');discount=Math.floor(final*v.discount_percent/100);final-=discount;v.status='used';v.used_order_id=uid('ORD')}const ord={id:Date.now(),order_id:v?.used_order_id||uid('ORD'),product_id:p.product_id,seller_id:p.seller_id,buyer_id:u.id,name:p.name,status:'pending',original_price:p.price,discount_amount:discount,final_price:final,voucher_code:body.voucher_code||'',email:body.email,whatsapp:body.whatsapp,address:body.address,created_at:new Date().toISOString()};d.orders.push(ord);if(v){const c=d.coins[u.id]||{balance:0};c.balance=(c.balance||0)+100;d.coins[u.id]=c;ord.bonus_vncoins=100}d.notifications.push({id:Date.now()+3,user_id:u.id,title:'Pesanan dibuat',body:`Pesanan ${ord.order_id} berhasil dibuat.`,is_read:false,created_at:new Date().toISOString()});saveDb(d);return{ok:true,order_id:ord.order_id,final_price:final,bonus_vncoins:ord.bonus_vncoins||0}}
if(a==='orders')return{orders:d.orders.filter(x=>x.buyer_id===u.id||x.seller_id===u.id).sort((a,b)=>b.id-a.id)}
if(a==='order-status'){const o=d.orders.find(x=>x.order_id===body.order_id&&x.seller_id===u.id);if(!o)throw new Error('Order tidak ditemukan.');o.status=body.status;o.reason=body.reason||'';saveDb(d);return{ok:true}}
if(a==='notifications'){return{notifications:d.notifications.filter(x=>x.user_id===u.id).sort((a,b)=>b.id-a.id)}}
if(a==='notifications-read'){d.notifications.filter(x=>x.user_id===u.id).forEach(x=>x.is_read=true);saveDb(d);return{ok:true}}
if(a==='chat-create'){const c={id:Date.now(),type:body.type||'cs',product_id:body.product_id||null,user_id:u.id,status:'open',created_at:new Date().toISOString()};d.chats.push(c);saveDb(d);return{chat_id:c.id}}
if(a==='chats')return{chats:d.chats.filter(x=>x.user_id===u.id).sort((a,b)=>b.id-a.id)}
if(a==='messages')return{messages:d.messages.filter(x=>x.chat_id===Number(qs.chat_id))}
if(a==='send-message'){const c=d.chats.find(x=>x.id===Number(body.chat_id)&&x.user_id===u.id);if(!c)throw new Error('Chat tidak ditemukan.');d.messages.push({id:Date.now(),chat_id:c.id,sender_name:u.username,is_system:false,body:body.message,created_at:new Date().toISOString()});saveDb(d);return{ok:true}}
if(a==='report'){d.audit.push({id:Date.now(),type:'report',user_id:u.id,product_id:body.product_id,reason:body.reason,details:body.details,created_at:new Date().toISOString()});saveDb(d);return{ok:true}}
if(a==='site-settings'){return{settings:d.settings}};
if(a==='owner-save-settings'){if(u?.role!=='owner')throw new Error('Hanya Owner yang dapat mengubah pengaturan situs.');const allowed=['siteTitle','siteSubtitle','announcement','background','overlay','accent','accent2','maintenance','serverIp','serverPort','serverVersions'];for(const k of allowed)if(body[k]!==undefined)d.settings[k]=body[k];saveDb(d);return{ok:true,settings:d.settings}};
if(a==='set-role'){if(u?.role!=='owner')throw new Error('Hanya Owner yang dapat mengatur role.');const target=d.users.find(x=>x.email.toLowerCase()===String(body.email||'').trim().toLowerCase());if(!target)throw new Error('User dengan email tersebut tidak ditemukan.');if(target.id===u.id)throw new Error('Role Owner tidak dapat diubah dari panel ini.');const role=String(body.role||'admin');if(!['customer','admin','admin_cs','staff'].includes(role))throw new Error('Role tidak valid.');target.role=role;d.notifications.push({id:Date.now()+Math.random(),user_id:target.id,title:'Role akun diperbarui',body:`Role kamu sekarang: ${role}.`,is_read:false,created_at:new Date().toISOString()});d.audit.push({id:Date.now()+Math.random(),type:'role_change',actor_id:u.id,target_user_id:target.id,role,created_at:new Date().toISOString()});saveDb(d);return{ok:true,user:{id:target.id,username:target.username,email:target.email,role:target.role}}};
if(a==='remove-admin'){if(u?.role!=='owner')throw new Error('Hanya Owner yang dapat menghapus Admin.');const target=d.users.find(x=>x.id===Number(body.user_id));if(!target)throw new Error('User tidak ditemukan.');if(target.role!=='admin')throw new Error('User ini bukan Admin.');target.role='customer';d.notifications.push({id:Date.now()+Math.random(),user_id:target.id,title:'Role Admin dicabut',body:'Role Admin kamu telah dicabut oleh Owner.',is_read:false,created_at:new Date().toISOString()});d.audit.push({id:Date.now()+Math.random(),type:'role_change',actor_id:u.id,target_user_id:target.id,role:'customer',created_at:new Date().toISOString()});saveDb(d);return{ok:true}};
if(a==='warn-user'){if(!['owner','admin','admin_cs','staff'].includes(u?.role))throw new Error('Akses staff diperlukan.');const target=d.users.find(x=>x.id===Number(body.user_id));if(!target)throw new Error('User tidak ditemukan.');const reason=String(body.reason||'Peringatan dari staff.').trim();const w={id:Date.now()+Math.random(),user_id:target.id,actor_id:u.id,actor_name:u.username,reason,created_at:new Date().toISOString()};d.warnings.push(w);d.notifications.push({id:Date.now()+Math.random(),user_id:target.id,title:'⚠️ Peringatan Akun',body:reason,is_read:false,created_at:new Date().toISOString()});d.audit.push({id:Date.now()+Math.random(),type:'warning',actor_id:u.id,target_user_id:target.id,reason,created_at:w.created_at});saveDb(d);return{ok:true,warning:w}};
if(a==='user-warnings'){const targetId=Number(body.user_id||qs.user_id||u.id);if(targetId!==u.id&&!['owner','admin','admin_cs','staff'].includes(u?.role))throw new Error('Akses ditolak.');return{warnings:d.warnings.filter(x=>x.user_id===targetId).sort((a,b)=>b.id-a.id)}};
if(a==='admin-chats'){if(!['owner','admin','admin_cs','staff'].includes(u?.role))throw new Error('Akses staff diperlukan.');return{chats:d.chats.slice().sort((a,b)=>b.id-a.id).map(c=>({...c,user:(d.users.find(x=>x.id===c.user_id)||{}).username||'User',email:(d.users.find(x=>x.id===c.user_id)||{}).email||'',claim:d.chatClaims[c.id]||null}))}};
if(a==='claim-chat'){if(!['owner','admin','admin_cs','staff'].includes(u?.role))throw new Error('Akses staff diperlukan.');const c=d.chats.find(x=>x.id===Number(body.chat_id));if(!c)throw new Error('Chat tidak ditemukan.');if(d.chatClaims[c.id]&&d.chatClaims[c.id].user_id!==u.id)throw new Error(`Request Message Udah Di Claim (${d.chatClaims[c.id].username}) Jadi Lu Udah Gak Bisa`);d.chatClaims[c.id]={user_id:u.id,username:u.username,claimed_at:new Date().toISOString()};c.claimed_by=u.id;c.status='claimed';d.messages.push({id:Date.now()+Math.random(),chat_id:c.id,sender_name:'SYSTEM',is_system:true,body:`${u.username} joined the chat`,created_at:new Date().toISOString()});saveDb(d);return{ok:true,claim:d.chatClaims[c.id]}};
if(a==='admin-messages'){if(!['owner','admin','admin_cs','staff'].includes(u?.role))throw new Error('Akses staff diperlukan.');const c=d.chats.find(x=>x.id===Number(qs.chat_id));if(!c)throw new Error('Chat tidak ditemukan.');return{messages:d.messages.filter(x=>x.chat_id===c.id)}};
if(a==='admin-send-message'){if(!['owner','admin','admin_cs','staff'].includes(u?.role))throw new Error('Akses staff diperlukan.');const c=d.chats.find(x=>x.id===Number(body.chat_id));if(!c)throw new Error('Chat tidak ditemukan.');const claim=d.chatClaims[c.id];if(claim&&claim.user_id!==u.id)throw new Error(`Chat sudah di-claim oleh ${claim.username}.`);if(!claim)d.chatClaims[c.id]={user_id:u.id,username:u.username,claimed_at:new Date().toISOString()};d.messages.push({id:Date.now()+Math.random(),chat_id:c.id,sender_name:u.username,is_system:false,body:String(body.message||'').trim(),created_at:new Date().toISOString()});d.notifications.push({id:Date.now()+Math.random(),user_id:c.user_id,title:`[CS] Pesan dari ${u.username}`,body:String(body.message||''),is_read:false,created_at:new Date().toISOString()});saveDb(d);return{ok:true}};
if(a==='admin-close-chat'){if(!['owner','admin','admin_cs','staff'].includes(u?.role))throw new Error('Akses staff diperlukan.');const c=d.chats.find(x=>x.id===Number(body.chat_id));if(!c)throw new Error('Chat tidak ditemukan.');if(d.chatClaims[c.id]&&d.chatClaims[c.id].user_id!==u.id&&u.role!=='owner')throw new Error('Chat di-claim admin lain.');c.status='closed';saveDb(d);return{ok:true}};
if(a==='add-music'){if(u?.role!=='owner')throw new Error('Hanya Owner yang dapat menambah musik.');const url=String(body.url||'').trim();if(!/^https?:\/\//i.test(url))throw new Error('URL musik harus dimulai http:// atau https://');const item={id:Date.now()+Math.random(),title:String(body.title||'Untitled').trim(),url,added_by:u.id,created_at:new Date().toISOString()};d.music.push(item);saveDb(d);return{ok:true,music:item}};
if(a==='remove-music'){if(u?.role!=='owner')throw new Error('Hanya Owner yang dapat menghapus musik.');d.music=d.music.filter(x=>x.id!==Number(body.id));saveDb(d);return{ok:true}};
if(a==='music-list'){return{music:d.music}};
if(a==='owner-users'){if(u?.role!=='owner')throw new Error('Hanya Owner yang dapat melihat panel ini.');return{users:d.users.map(x=>({id:x.id,username:x.username,email:x.email,role:x.role,created_at:x.created_at}))}};
if(a==='admin-users-search'){if(!['owner','admin','admin_cs','staff'].includes(u?.role))throw new Error('Akses staff diperlukan.');const q=String(qs.q||'').toLowerCase();return{users:d.users.filter(x=>(x.email+' '+x.username).toLowerCase().includes(q)).map(x=>({id:x.id,username:x.username,email:x.email,role:x.role}))}};
if(a==='admin-discount'){if(!['owner','admin'].includes(u?.role))throw new Error('Hanya Owner/Admin yang dapat mengatur diskon.');const percent=Math.max(0,Math.min(100,Number(body.percent)||0));const discount={id:Date.now()+Math.random(),percent,name:String(body.name||'Promo Veyltharyn').trim(),active:body.active!==false,created_by:u.id,created_at:new Date().toISOString()};d.discounts.push(discount);d.settings.announcement=discount.active?`${discount.name}: ${discount.percent}% OFF`:d.settings.announcement;saveDb(d);return{ok:true,discount}};
if(a==='admin-discounts'){if(!['owner','admin','admin_cs','staff'].includes(u?.role))throw new Error('Akses staff diperlukan.');return{discounts:d.discounts.slice().reverse()}};
if(a==='admin-delete-discount'){if(u?.role!=='owner')throw new Error('Hanya Owner yang dapat menghapus promo.');d.discounts=d.discounts.filter(x=>x.id!==Number(body.id));saveDb(d);return{ok:true}};
if(a==='logout'){localStorage.removeItem(SESSION);return{ok:true}}
if(a==='admin-update-product'){if(!['owner','admin','admin_cs','staff'].includes(u?.role))throw new Error('Akses admin diperlukan.');const p=d.products.find(x=>x.product_id===body.product_id&&x.status!=='deleted');if(!p)throw new Error('Produk tidak ditemukan.');if(body.name!==undefined)p.name=String(body.name).trim();if(body.description!==undefined)p.description=String(body.description).trim();if(body.price!==undefined)p.price=Math.max(0,Number(body.price)||0);if(body.category!==undefined)p.category=String(body.category).trim();saveDb(d);return{ok:true};}
if(a==='admin-products'){if(!['owner','admin','admin_cs','staff'].includes(u?.role))throw new Error('Akses admin diperlukan.');return{products:d.products.filter(x=>x.status!=='deleted').map(x=>({...x,seller:(d.users.find(z=>z.id===x.seller_id)||{}).username||'Seller'}))};}
if(a==='admin-users'){if(!['owner','admin','admin_cs','staff'].includes(u?.role))throw new Error('Akses admin diperlukan.');return{users:d.users.map(({password,...x})=>x)}};
if(a==='admin-reports'){if(!['owner','admin','admin_cs','staff'].includes(u?.role))throw new Error('Akses admin diperlukan.');return{reports:d.audit.filter(x=>x.type==='report')}};
if(a==='audit'){if(!['owner','admin','admin_cs','staff'].includes(u?.role))throw new Error('Akses admin diperlukan.');return{audit:d.audit}};
throw new Error('Fitur '+a+' belum tersedia di GitHub Pages mode.');}
